version: "3.5"

services:
  db:
    image: postgres:13.1-alpine
    container_name: chef_level_one_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_ENV}
    volumes:
      - ./db/table_recipes.sql:/docker-entrypoint-initdb.d/table_recipes.sql
    ports:
      - "5432:5432"
  webservice:
    image: node:14
    container_name: chef_level_one_webservice
    volumes:
      - ./webservice:/code/webservice/
      - ./sh:/usr/local/sh/
    command: /bin/sh 'usr/local/sh/webservice.sh'
    ports:
      - 3333:3333
    depends_on:
      - db
  app:
    image: node:14
    container_name: chef_level_one_app
    volumes:
      - ./app:/code/app/
      - ./sh:/usr/local/sh/
    command: /bin/sh 'usr/local/sh/app.sh'
    ports:
      - 3000:3000
    depends_on:
      - webservice