version: "3.9"

services:
  db:
    image: postgres:13.1-alpine
    container_name: chef_level_one_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_ENV}
    volumes:
      - ./db/table_recipes.sql:/docker-entrypoint-initdb.d/table_recipes.sql
    ports:
      - 5432:5432

  webservice:
    build:
      context: .
      dockerfile: webservice.DockerFile
    container_name: chef_level_one_webservice
    restart: always
    volumes:
      - ./webservice:/usr/src/code/webservice
      - /usr/src/code/webservice/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: app.DockerFile
    container_name: chef_level_one_app
    environment:
      - REACT_APP_WEBSERVICE_BASE_URL=${WEBSERVICE_API_URL}
    restart: always
    volumes:
      - ./app:/usr/src/code/app
      - /usr/src/code/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - webservice
